model: fff.FiberModel

val_every_n_epoch: 5
cond_dim: 512
compute_c_on_fly: True
noise: 0.
ae_conditional: True
load_subject_model: True
latent_distribution:
  name: "normal"
data_set:
  name: ldct
  root: /home/hd/hd_hd/hd_gu452/ldct_data
  condition: lowdose
  data: highdose
  patchsize: 512
  resize_to: 224
  subject_model_type: PrecompiledModel
  subject_model_path: notebooks/SubjectModels/saved_models/BiomedClip.pt

eval_all: True
loss_weights:
  # ae_elbo: 0.1
  ae_noisy_l1_reconstruction: 1
  perceptual_loss: 120
  
max_epochs: 250

train_lossless_ae: True
vae: True
lossless_ae:
  model_spec:
    - name: fff.model.LDCTInvModel
      latent_dim: 1024
      ch_factor: 48
  cond_embedding_shape: [64, 224, 224]
  cond_embedding_network:
    - name: fff.model.ConvolutionalNeuralNetwork
      latent_dim: &latent_dim 512
      ch_factor: 1
      image_shape: [64, 224, 224]
      encoder_spec: []
      decoder_spec:
        - [128, 3]
        - [128, 4, 2, 1, 1]   # 2 → 4
        - [64, 4, 2, 1, 0]   # 4 → 8
        - [64, 4, 2, 1, 0]   # 8 → 16
        - [32, 4, 2, 1, 0]    # 16 → 32
        - [32, 4, 2, 1, 0]    # 32 → 64
        - [64, 4, 2, 1, 0]    # 64 → 128
    - name: fff.model.ResNet
      latent_dim: 512
      layers_spec:
        - [512, 512]
  use_condition_decoder: True



density_model:
  - name: fff.model.Identity


condition_embedder:
  - name: fff.model.ResNet
    latent_dim: 512
    layers_spec:
      - [512, 512, 512]


lr_scheduler: "onecyclelr"
optimizer:
  name: adam
  lr: 0.0005

batch_size: 64

model_checkpoint:
  monitor: auto
  save_last: true

