model: fff.SomeModel
#accelerator: "cpu"

noise: 0.01
data_set:
  name: emnist
  root: data
  conditional: False

loss_weights:
  ae_lamb_reconstruction: 2000
  #sqr_reconstruction: 10
  ae_elbo: 1
  #z std: 1
  #nll: 1
max_epochs: 500

vae: True
train_lossless_ae: True
lossless_ae:
  - name: fff.model.ConvolutionalNeuralNetwork
    latent_dim: &latent_dim 100
    ch_factor: 32
    encoder_spec: 
      - [1,4,2,1]
      - [2,4,2,1]
      - [4,4,2,1]
      - [8,4,2,1]
    decoder_spec:
      - [8,4]
      - [4,3,2,1]
      - [2,3,2,1,1]
      - [1,3,2,1,1]
  - name: fff.model.ResNet
    latent_dim: 48
    layers_spec:
      - [512, 512, 512]
      - [512, 512, 512]
      - [512, 512, 512]
density_model:
  - name: fff.model.Identity

lr_scheduler: "onecyclelr"
optimizer:
  name: adam
  lr: 0.0005

batch_size: 512
#load_models_path: "lightning_logs/16VAE_3/version_0/checkpoints/last.ckpt"
