model: fff.FreeFormFlow

latent_distribution:
  name: "normal"
data_set:
  name: 2moons
  # num_simulations: ... must be specified in separate config file
  conditional: True

noise: 0.

loss_weights:
  nll: 1
  noisy_reconstruction: 10

models:
  - name: fff.model.ResNet
    latent_dim: 2
    layers_spec:
      - [256, 256]
      - [256, 256]
      - [256, 256]
      - [256, 256]

condition_embedder:
  - name: fff.model.ResNet
    latent_dim: 16
    layers_spec:
      - [256, 256]


lr_scheduler: "onecyclelr"

batch_size: 128
optimizer:
  name: adam
  lr: 0.0004
  #weight_decay: 0.0001

max_epochs: 100

num_workers: 4
gradient_clip: 3.0
accelerator: "cpu"
