model: fff.FreeFormInjectiveFlow

noise: 0.
data_set:
  name: mnist_split
  root: data
  conditional: true
  path: "28noisy_AE"

loss_weights:
  nll: 1
  noisy_reconstruction: 10000
  masked_reconstruction: 100
  cnew_reconstruction: 100
  #cdel_reconstruction: 10000
max_epochs: 1000

models:
  - name: fff.model.ConvolutionalNeuralNetwork
    latent_dim: &latent_dim 256
    ch_factor: 32
  - name: fff.model.ResNet
    latent_dim: *latent_dim
    layers_spec:
      - [512, 512]
      - [512, 512]
      - [512, 512]
      - [512, 512]

lr_scheduler: "onecyclelr"
optimizer:
  name: adam
  lr: 0.0005

batch_size: 256
