model: fff.FreeFormFlow

latent_distribution:
  name: "transformed_normal"
data_set:
  name: moons_split
  fix_noise: 0.01
  # num_simulations: ... must be specified in separate config file
  conditional: True
  path: "fif_moons"

noise: 0.

loss_weights:
  nll: 10
  latent_reconstruction: 1
mask_dims: 1

train_models: False
train_transform: True
models:
  - name: fff.model.Identity
transform:
  name: fff.model.DenoisingFlow
  data_dim: 2
  latent_dim: 2
  inn_spec:
    - ["PermuteRandom", {}, 0]
    - ["RationalQuadraticSpline", {"bins": 8}, [32, 32]]
    - ["PermuteRandom", {}, 0]
    - ["RationalQuadraticSpline", {"bins": 8}, [32, 32]]
    - ["PermuteRandom", {}, 0]
    - ["RationalQuadraticSpline", {"bins": 8}, [32, 32]]
      #- ["RationalQuadraticSpline", {"bins": 8, "min_bin_sizes": [0.2,0.2]}, [256]]
    - ["PermuteRandom", {}, 0]

lr_scheduler: "onecyclelr"

batch_size: 128
optimizer:
  name: adam
  lr: 0.0004
  #weight_decay: 0.0001

max_epochs: 100

num_workers: 4
gradient_clip: 3.0
accelerator: "cpu"
