model: fff.FreeFormFlow

latent_distribution:
  name: "transformed_normal"
data_set:
  name: moons_split
  # num_simulations: ... must be specified in separate config file
  conditional: True
  path: "fif_moons"

noise: 0.01
  #cnew_every: 2

loss_weights:
  nll: 1
  coarse_supervised: 1

train_models: False
train_transform: True
models:
  - name: fff.model.Identity
transform:
  name: fff.model.MultilevelFlow
  phase: False
  data_dim: 2
  latent_dim: 2
  inn_spec:
    - ["PermuteRandom", {}, 0]
    - ["RationalQuadraticSpline", {"bins": 8, "min_bin_sizes": [0.5,0.5]}, [128, 256]]
    - ["PermuteRandom", {}, 0]
    - ["RationalQuadraticSpline", {"bins": 8, "min_bin_sizes": [0.5,0.5]}, [256, 256]]
    - ["PermuteRandom", {}, 0]
    - ["RationalQuadraticSpline", {"bins": 8, "min_bin_sizes": [0.5,0.5]}, [256, 256]]
      #- ["RationalQuadraticSpline", {"bins": 8, "min_bin_sizes": [0.2,0.2]}, [256]]
    - ["PermuteRandom", {}, 0]

lr_scheduler: "onecyclelr"

batch_size: 2048
optimizer:
  name: adam
  lr: 0.0002
  weight_decay: 0.0001

max_epochs: 100

num_workers: 4
gradient_clip: 2.0
accelerator: "gpu"
