model: fff.FreeFormFlow

latent_distribution:
  name: "transformed_normal"
data_set:
  name: moons_split
  # num_simulations: ... must be specified in separate config file
  conditional: True
  path: "fif_moons"

noise: 0.05

loss_weights:
  nll: 1

train_models: False
train_transform: True
models:
  - name: fff.model.Identity
transform:
  name: fff.model.InjectiveFlow
  data_dim: 2
  latent_dim: 2
  inn_spec:
    - ["PermuteRandom", {}, 0]
    - ["RationalQuadraticSpline", {"bins": 8}, [512]]
      #- ["RationalQuadraticSpline", {"bins": 8, "min_bin_sizes": [0.2,0.2]}, [256]]
    - ["PermuteRandom", {}, 0]
    - ["RationalQuadraticSpline", {"bins": 8}, [512]]
    - ["PermuteRandom", {}, 0]
    - ["RationalQuadraticSpline", {"bins": 8}, [512]]
    - ["PermuteRandom", {}, 0]
    - ["RationalQuadraticSpline", {"bins": 8}, [512]]
    - ["PermuteRandom", {}, 0]
    - ["RationalQuadraticSpline", {"bins": 8}, [512]]
    - ["PermuteRandom", {}, 0]
    - ["RationalQuadraticSpline", {"bins": 8}, [512]]
    - ["PermuteRandom", {}, 0]
    - ["RationalQuadraticSpline", {"bins": 8}, [512]]
    - ["PermuteRandom", {}, 0]
    - ["RationalQuadraticSpline", {"bins": 8}, [512]]
    - ["PermuteRandom", {}, 0]
    - ["RationalQuadraticSpline", {"bins": 8}, [512]]
    - ["PermuteRandom", {}, 0]

lr_scheduler: "onecyclelr"

batch_size: 1024
optimizer:
  name: adam
  lr: 0.0005
  #weight_decay: 0.0001

max_epochs: 200

num_workers: 4
gradient_clip: 3.0
accelerator: "gpu"
