model: fff.FreeFormInjectiveFlow

noise: 0.01
latent_distribution:
  name: "transformed_normal"
data_set:
  name: mnist_split
  root: data
  conditional: True
  path: "16EMnist_F3F"

loss_weights:
  nll: 1
  latent_reconstruction: 100
  #noisy_reconstruction: 100
  masked_reconstruction: 1
  #cnew_reconstruction: 10
  #z_sample_reconstruction: 1000
max_epochs: 200
#warm_up_epochs: [15, 100]
#warm_up_fiber: [35, 40]

train_models: False
train_transform: True
vae: True
models:
  - name: fff.model.ConvolutionalNeuralNetwork
    latent_dim: 100
    ch_factor: 32
    encoder_spec: 
      - [2,4,2,1]
      - [4,4,2,1]
      - [8,4,2,1]
    decoder_spec:
      - [8,4]
      - [4,4,2,1]
      - [1,3,2,1,1]
  - name: fff.model.VarResNet
    latent_dim: &latent_dim 64
    layers_spec:
      - [512, 512]
      - [512, 512]
transform:
  name: fff.model.ResNet
  data_dim: *latent_dim
  latent_dim: 61
  layers_spec:
    - [512, 512]
    - [512, 512]
    - [512, 512]

lr_scheduler: "onecyclelr"
optimizer:
  name: adam
  lr: 0.002

batch_size: 512
load_models_path: "lightning_logs/16VAE_3/version_0/checkpoints/last.ckpt"
  #load_transform_path: "lightning_logs/16_f48f_011_log/version_0/checkpoints/last.ckpt"
