model: fff.FreeFormInjectiveFlow

noise: 0.
latent_distribution:
  name: "transformed_normal"
data_set:
  name: mnist_split
  root: data
  conditional: true
  path: "16Mnist_AE"

loss_weights:
  nll: 1
  latent_reconstruction: 1000
  #noisy_reconstruction: 100
  #masked_reconstruction: 1
  #cnew_reconstruction: 1000
  #z_sample_reconstruction: 1
max_epochs: 1000
#warm_up_fiber: [35, 40]

train_models: False
train_transform: True
vae: True
models:
  - name: fff.model.ConvolutionalNeuralNetwork
    latent_dim: 100
    ch_factor: 32
    encoder_spec: 
      - [2,4,2,1]
      - [4,4,2,1]
      - [8,4,2,1]
    decoder_spec:
      - [8,4]
      - [4,4,2,1]
      - [1,3,2,1,1]
  - name: fff.model.VarResNet
    latent_dim: &latent_dim 64
    layers_spec:
      - [512, 512]
      - [512, 512]
transform:
  name: fff.model.InjectiveFlow
  data_dim: *latent_dim
  latent_dim: *latent_dim
  inn_spec:
      #- ["PermuteRandom", {}, 0]
      #- ["RationalQuadraticSpline", {"bins": 8}, [128]]
    - ["AllInOneBlock", {}, [256]]
    - ["AllInOneBlock", {}, [256]]
    - ["AllInOneBlock", {}, [256]]
    - ["AllInOneBlock", {}, [256]]
    - ["AllInOneBlock", {}, [256]]
    - ["AllInOneBlock", {}, [256]]
    - ["AllInOneBlock", {}, [256]]
    - ["AllInOneBlock", {}, [256]]
    - ["AllInOneBlock", {}, [256]]
    - ["AllInOneBlock", {}, [256]]
    - ["AllInOneBlock", {}, [256]]
    - ["AllInOneBlock", {}, [256]]
    - ["AllInOneBlock", {}, [256]]
    - ["AllInOneBlock", {}, [256]]
    - ["AllInOneBlock", {}, [256]]
    - ["AllInOneBlock", {}, [256]]
    - ["AllInOneBlock", {}, [256]]
    - ["AllInOneBlock", {}, [256]]
    - ["AllInOneBlock", {}, [256]]
    - ["AllInOneBlock", {}, [256]]

lr_scheduler: "onecyclelr"
optimizer:
  name: adam
  lr: 0.001

batch_size: 512
load_models_path: "lightning_logs/16VAE_3/version_0/checkpoints/last.ckpt"
#load_transform_path: "lightning_logs/16aznc_i_lr2/version_0/checkpoints/last.ckpt"
