model: fff.FreeFormInjectiveFlow

noise: 0.01
latent_distribution:
  name: "transformed_normal"
data_set:
  name: mnist_split
  root: data
  conditional: True
  path: "EMnist_Class"

loss_weights:
  nll: 1
  masked_reconstruction: 1
  #latent_reconstruction: 10
  cnew_reconstruction: 10
  #z_sample_reconstruction: 1
  #mask_dims: 16
max_epochs: 50
#warm_up_fiber: [35, 40]

train_models: False
train_transform: True
vae: True
models:
  - name: fff.model.ConvolutionalNeuralNetwork
    latent_dim: 100
    ch_factor: 32
    encoder_spec: 
      - [2,4,2,1]
      - [4,4,2,1]
      - [8,4,2,1]
    decoder_spec:
      - [8,4]
      - [4,4,2,1]
      - [1,3,2,1,1]
  - name: fff.model.VarResNet
    latent_dim: &latent_dim 64
    layers_spec:
      - [512, 512]
      - [512, 512]
transform:
  name: fff.model.InjectiveFlow
  data_dim: *latent_dim
  latent_dim: *latent_dim
  inn_spec:
    #- ["PermuteRandom", {}, 0]
    #- ["RationalQuadraticSpline", {"bins": 8, "min_bin_sizes": [0.2,0.2]}, [128]]
    #- ["PermuteRandom", {}, 0]
    - ["AllInOneBlock", {}, [512]]
    - ["AllInOneBlock", {}, [512]]
    - ["AllInOneBlock", {}, [512]]
    - ["AllInOneBlock", {}, [512]]
    - ["AllInOneBlock", {}, [512]]
    - ["AllInOneBlock", {}, [512]]
    - ["AllInOneBlock", {}, [512]]
    - ["AllInOneBlock", {}, [512]]
    - ["AllInOneBlock", {}, [512]]
    - ["AllInOneBlock", {}, [512]]
    - ["AllInOneBlock", {}, [512]]
    - ["AllInOneBlock", {}, [512]]
    - ["AllInOneBlock", {}, [512]]
    - ["AllInOneBlock", {}, [512]]
    - ["AllInOneBlock", {}, [512]]
    - ["AllInOneBlock", {}, [512]]
    - ["AllInOneBlock", {}, [512]]
    - ["AllInOneBlock", {}, [512]]
    - ["AllInOneBlock", {}, [512]]
    - ["AllInOneBlock", {}, [512]]
    - ["AllInOneBlock", {}, [512]]
    - ["AllInOneBlock", {}, [512]]
    - ["AllInOneBlock", {}, [512]]
    - ["AllInOneBlock", {}, [512]]
    - ["AllInOneBlock", {}, [512]]
    - ["AllInOneBlock", {}, [512]]
    - ["AllInOneBlock", {}, [512]]
    - ["AllInOneBlock", {}, [512]]
    - ["AllInOneBlock", {}, [512]]
    - ["AllInOneBlock", {}, [512]]
    - ["AllInOneBlock", {}, [512]]
    - ["AllInOneBlock", {}, [512]]
    - ["AllInOneBlock", {}, [512]]
    - ["AllInOneBlock", {}, [512]]
    - ["AllInOneBlock", {}, [512]]
    - ["AllInOneBlock", {}, [512]]
    - ["AllInOneBlock", {}, [512]]
    - ["AllInOneBlock", {}, [512]]
    - ["AllInOneBlock", {}, [512]]
    - ["AllInOneBlock", {}, [512]]

lr_scheduler: "onecyclelr"
optimizer:
  name: adam
  lr: 0.002
gradient_clip: 3.0

batch_size: 512
load_models_path: "lightning_logs/E16VAE_3_wodo/version_0/checkpoints/last.ckpt"
#load_transform_path: "lightning_logs/16vae_if2/version_0/checkpoints/last.ckpt"
