model: fff.FreeFormInjectiveFlow

noise: 0.
latent_distribution:
  name: "transformed_normal"
data_set:
  name: mnist_split
  root: data
  conditional: true
  path: "8Mnist_FIF5"

loss_weights:
  nll: 1
  #noisy_reconstruction: 100
  #masked_reconstruction: 1
  #cnew_reconstruction: 1
  #z_sample_reconstruction: 1
max_epochs: 1500
#warm_up_fiber: [35, 40]

train_models: False
train_transform: True
models:
  - name: fff.model.ConvolutionalNeuralNetwork
    latent_dim: &latent_dim 59
    ch_factor: 16
    encoder_spec: 
      - [1,3,1,1]
      - [2,3,2,1]
      - [4,3,2,1]
    decoder_spec:
      - [4,4]
      - [1,3,2,1,1]
  - name: fff.model.ResNet
    latent_dim: *latent_dim
    layers_spec:
      - [256, 256]
      - [256, 256]
      - [256, 256]
transform:
  name: fff.model.InjectiveFlow
  data_dim: *latent_dim
  latent_dim: *latent_dim
  inn_spec:
      #- ["PermuteRandom", {}, 0]
      #- ["RationalQuadraticSpline", {"bins": 8}, [128]]
    - ["AllInOneBlock", {}, [128]]
    - ["AllInOneBlock", {}, [128]]
    - ["AllInOneBlock", {}, [128]]
    - ["AllInOneBlock", {}, [128]]
    - ["AllInOneBlock", {}, [128]]
    - ["AllInOneBlock", {}, [128]]
    - ["AllInOneBlock", {}, [128]]
    - ["AllInOneBlock", {}, [128]]
    - ["AllInOneBlock", {}, [128]]
    - ["AllInOneBlock", {}, [128]]
    - ["AllInOneBlock", {}, [128]]
    - ["AllInOneBlock", {}, [128]]
    - ["AllInOneBlock", {}, [128]]
    - ["AllInOneBlock", {}, [128]]
    - ["AllInOneBlock", {}, [128]]
    - ["AllInOneBlock", {}, [128]]
    - ["AllInOneBlock", {}, [128]]
    - ["AllInOneBlock", {}, [128]]
    - ["AllInOneBlock", {}, [128]]
    - ["AllInOneBlock", {}, [128]]

lr_scheduler: "onecyclelr"
optimizer:
  name: adam
  lr: 0.002

batch_size: 256
load_models_path: "lightning_logs/8ph_5/version_0/checkpoints/last.ckpt"
#load_transform_path: "lightning_logs/8a-i20_lbs_fast/version_0/checkpoints/last.ckpt"
