model: fff.FreeFormInjectiveFlow

noise: 0.
data_set:
  name: mnist_split
  root: data
  conditional: true
  path: "16Mnist_AE"

loss_weights:
  nll: 1
  noisy_reconstruction: 10000
  masked_reconstruction: 100
  cnew_reconstruction: 100
  z_sample_reconstruction: 100
max_epochs: 2000
warm_up_fiber: [25, 30]

models:
  - name: fff.model.ConvolutionalNeuralNetwork
    latent_dim: &latent_dim 100
    ch_factor: 32
    encoder_spec: 
      - [2,4,2,1]
      - [4,4,2,1]
      - [8,4,2,1]
    decoder_spec:
      - [8,4]
      - [4,4,2,1]
      - [1,3,2,1,1]
  - name: fff.model.ResNet
    latent_dim: *latent_dim
    layers_spec:
      - [512, 512]
      - [512, 512]
      - [512, 512]
      - [512, 512]


lr_scheduler: "onecyclelr"
optimizer:
  name: adam
  lr: 0.0005

batch_size: 256
