model: fff.FreeFormInjectiveFlow
#accelerator: "cpu"

noise: 0.05
data_set:
  name: mnist_ds
  root: data
  conditional: False
    #digit: 4

loss_weights:
  noisy_reconstruction: 100
  z_reconstruction_encoder: 10
  #sqr_reconstruction: 10
  #z std: 1
  nll: 1
max_epochs: 200

train_models: True
models:
  - name: fff.model.ConvolutionalNeuralNetwork
    latent_dim: &latent_dim 100
    ch_factor: 32
    encoder_spec: 
      - [2,4,2,1]
      - [4,4,2,1]
      - [8,4,2,1]
    decoder_spec:
      - [8,4]
      - [4,4,2,1]
      - [1,3,2,1,1]
  - name: fff.model.ResNet
    latent_dim: 5
    dropout: 0.5
    layers_spec:
      - [128, 128]
      - [128, 128]

        #lr_scheduler: "onecyclelr"
optimizer:
  name: adam
  lr: 0.0005
  weight_decay: 0.01

batch_size: 512
#load_models_path: "lightning_logs/16VAE_3/version_0/checkpoints/last.ckpt"
