model: fff.FreeFormInjectiveFlow

noise: 0.01
data_set:
  name: mnist_ds
  root: data
  conditional: True

loss_weights:
  classification: 0
  noisy_reconstruction: 1
max_epochs: 50

train_models: True
models:
  - name: fff.model.ConvolutionalNeuralNetwork
    latent_dim: &latent_dim 10
    ch_factor: 32
    encoder_spec: 
      - [2,4,2,1]
      - [4,4,2,1]
      - [8,4,2,1]
    decoder_spec:
      - [8,4]
      - [4,4,2,1]
      - [1,3,2,1,1]
  - name: fff.model.ResNet
    classification: true
    latent_dim: 10
    dropout: 0.5
    layers_spec:
      - [32, 32]
      - [32, 32]

lr_scheduler: "onecyclelr"
optimizer:
  name: adam
  lr: 0.001

batch_size: 512
load_models_path: "lightning_logs/GT_Class_decoder/version_3/checkpoints/last.ckpt"
