model: fff.FreeFormInjectiveFlow

noise: 0.01
data_set:
  name: mnist_ds
  root: data

loss_weights:
  noisy_reconstruction: 1000
  nll: 1
max_epochs: 2000

models:
  - name: fff.model.ConvolutionalNeuralNetwork
    latent_dim: &latent_dim 8
    ch_factor: 32
  - name: fff.model.ResNet
    latent_dim: *latent_dim
    layers_spec:
      - [512, 512]
      - [512, 512]
      - [512, 512]

lr_scheduler: "onecyclelr"
optimizer:
  name: adam
  lr: 0.001

batch_size: 512
