model: fff.FreeFormInjectiveFlow
#accelerator: "cpu"

noise: 0.01
data_set:
  name: saved_mnist
  root: data/cc_mnist
  conditional: False

loss_weights:
  noisy_reconstruction: 2000
  #sqr_reconstruction: 10
  kl: 1
  #z std: 2
  #nll: 1
max_epochs: 500

eval_all: False
vae: True
train_models: True
models:
  - name: fff.model.ConvolutionalNeuralNetwork
    latent_dim: &latent_dim 100
    ch_factor: 32
    encoder_spec: 
      - [3, 4, 2, 1]
      - [6, 4, 2, 1]
      - [8, 4, 2, 1]
      - [10, 4, 2, 1]
    decoder_spec:
      - [10, 4]
      - [8, 3, 2, 1]
      - [6, 3, 2, 1, 1]
      - [3, 3, 2, 1, 1]
  - name: fff.model.VarResNet
    latent_dim: 54
    layers_spec:
      - [512, 512, 512]
      - [512, 512, 512]
      - [512, 512, 512]
lr_scheduler: "onecyclelr"
optimizer:
  name: adam
  lr: 0.0002

batch_size: 512
  #load_models_path: "lightning_logs/C_vae/checkpoints/last.ckpt"
