model: fff.FreeFormInjectiveFlow

data_set:
  name: 2moons

noise: 0.1  # This is varied

lr_scheduler: "onecyclelr"

train_models: True
loss_weights:
  nll: 1
  noisy_reconstruction: 10  # This is varied in the paper

models:
  - name: fff.model.ResNet
    latent_dim: 1
    layers_spec:
      - [512, 512, 512]

lr_scheduler: "onecyclelr"
batch_size: 1024
optimizer:
  name: adam
  lr: 0.0001
max_epochs: 200

#accelerator: "cpu"
#num_workers: 0
