model: fff.FreeFormInjectiveFlow

latent_distribution:
  name: "normal"
load_subject_model: True
data_set:
  name: moons_split
  # num_simulations: ... must be specified in separate config file
  conditional: True
  path: "2moons_demo1"

noise: 0.01

loss_weights:
  nll: 1
  noisy_reconstruction: 100

train_models: True
models:
  - name: fff.model.ResNet
    latent_dim: 1
    layers_spec:
      - [512, 512]
      - [512, 512]
      - [512, 512]

lr_scheduler: "onecyclelr"

batch_size: 128
optimizer:
  name: adam
  lr: 0.001
  #weight_decay: 0.0001

max_epochs: 1000

num_workers: 4
gradient_clip: 3.0
accelerator: "gpu"
