model: fff.FiberModel

noise: 0.
load_subject_model: False
betas_max: 0.04
beta_schedule: "linear"
fiber_loss_every: 20
latent_distribution:
  name: "normal"
data_set:
  name: mnist_split
  root: data
  conditional: true
  path: "16EMNIST_F5F_demo"

loss_weights:
  diff_mse: 1
max_epochs: 400
#warm_up_epochs: [40, 60]
#warm_up_fiber: [15, 100]

train_lossless_ae: False
vae: True
lossless_ae:
  - name: fff.model.ConvolutionalNeuralNetwork
    latent_dim: 100
    ch_factor: 32
    encoder_spec: 
      - [2,4,2,1]
      - [4,4,2,1]
      - [8,4,2,1]
    decoder_spec:
      - [8,4]
      - [4,4,2,1]
      - [1,3,2,1,1]
  - name: fff.model.VarResNet
    latent_dim: &latent_dim 64
    layers_spec:
      - [512, 512]
      - [512, 512]
      - [512, 512]
density_model:
  - name: fff.model.DiffusionModel
    data_dim: *latent_dim
    num_heads: 4
    time_dim: 8
    hidden_dim: 64
    layers_spec:
      - [512, 512]
      - [512, 512]
      - [512, 512]
      - [512, 512]
      - [512, 512]
      - [512, 512]

lr_scheduler:
  name: "onecyclelr"
  kwargs:
    pct_start: 0.05
    
optimizer:
  name: adam
  lr: 0.001

batch_size: 512
load_lossless_ae_path: "lightning_logs/test/version_0/checkpoints/last.ckpt"
