model: fff.FiberModel

noise: 0.01
load_subject_model: True
load_lossless_ae_path: "lightning_logs/version_9/checkpoints/last.ckpt"
latent_distribution:
  name: "normal"
data_set:
  name: mnist_split
  root: data
  conditional: True
  path: "16EMNIST_F5F_demo"
  subject_model_path: "data/16EMNIST_F5F_demo/subject_model/checkpoints/last.ckpt"
  subject_model_type: FreeFormInjectiveFlow

loss_weights:
  nll: 1
  latent_reconstruction: 10
  #noisy_reconstruction: 100
  fiber_loss: 1
  #z_sample_reconstruction: 1000
max_epochs: 5
mask_dims: 1
#warm_up_epochs: [15, 100]
#warm_up_fiber: [35, 40]

train_lossless_ae: False
vae: True
lossless_ae:
  - name: fff.model.ConvolutionalNeuralNetwork
    latent_dim: 100
    ch_factor: 32
    encoder_spec: 
      - [2,4,2,1]
      - [4,4,2,1]
      - [8,4,2,1]
    decoder_spec:
      - [8,4]
      - [4,4,2,1]
      - [1,3,2,1,1]
  - name: fff.model.VarResNet
    latent_dim: &latent_dim 64
    layers_spec:
      - [512, 512]
      - [512, 512]
      - [512, 512]
density_model:
  - name: fff.model.ResNet
    data_dim: *latent_dim
    latent_dim: 59
    layers_spec:
      - [512, 512]
      - [512, 512]
      - [512, 512]

condition_embedder:
  - name: fff.model.ResNet
    latent_dim: 16
    layers_spec:
      - [256, 256]

lr_scheduler: "onecyclelr"
optimizer:
  name: adam
  lr: 0.002

batch_size: 512
load_lossless_ae_path: "lightning_logs/MNIST_VAE/version_0/checkpoints/last.ckpt"
  #load_transform_path: "lightning_logs/16_f48f_011_log/version_0/checkpoints/last.ckpt"
