model: fff.FiberModel

val_every_n_epoch: 10
cond_dim: 16384
noise: 0.
load_subject_model: True
load_lossless_ae_path: Y_fl50
compute_c_on_fly: True
latent_distribution:
  name: "normal"
data_set:
  name: ldct
  root: data/ldct
  condition: lowdose
  data: highdose
  subject_model_type: cnn10

eval_all: True
loss_weights:
  nll: 0.00001
  latent_reconstruction: 1
  fiber_loss: 1000
max_epochs: 500
#warm_up_epochs: [15, 100]
#warm_up_fiber: [35, 40]

train_lossless_ae: False
vae: True
ae_conditional: True
density_model:
  - name: fff.model.ResNet
    data_dim: 4096
    latent_dim: 4096
    layers_spec:
      - [6144, 6144]

condition_embedder:
  - name: fff.model.ConvolutionalNeuralNetwork
    latent_dim: 2048
    fc: True
    ch_factor: 64
    encoder_spec: 
      - [1,4,2,1]
      - [2,4,2,1]
      - [4,4,2,1]
      - [8,4,2,1]


lr_scheduler: "onecyclelr"
optimizer:
  name: adam
  lr: 0.00002

batch_size: 64

model_checkpoint:
  monitor: "auto"
  save_last: True
  every_n_epochs: 100
  save_top_k: 2
