model: fff.FiberModel

val_every_n_epoch: 10
cond_dim: 16384
load_lossless_ae_path: Y_fl50
compute_c_on_fly: True
noise: 0.
ae_conditional: True
load_subject_model: True
latent_distribution:
  name: "normal"
data_set:
  name: ldct
  root: data/ldct
  condition: lowdose
  data: highdose
  subject_model_type: cnn10

eval_all: True
loss_weights:
  nll: 1.
  fiber_loss: 10000
  ae_l1_reconstruction: 0.2
  fiber_loss_rec: 10000
  #latent_reconstruction: 10
  #fiber_loss: 100
  #z_sample_reconstruction: 1
max_epochs: 500
#warm_up_fiber: [35, 40]

train_lossless_ae: True
vae: True
density_model:
  - name: fff.model.INN
    latent_dim: 4096
    zero_init: True
    inn_spec:
      - ["AllInOneBlock", {}, [2048]]
      - ["AllInOneBlock", {}, [2048]]
      - ["AllInOneBlock", {}, [2048]]
      - ["AllInOneBlock", {}, [2048]]
      - ["AllInOneBlock", {}, [2048]]
      - ["AllInOneBlock", {}, [2048]]
      - ["AllInOneBlock", {}, [2048]]
      - ["AllInOneBlock", {}, [2048]]
      - ["AllInOneBlock", {}, [2048]]
      - ["AllInOneBlock", {}, [2048]]
      - ["AllInOneBlock", {}, [2048]]
      - ["AllInOneBlock", {}, [2048]]
      - ["AllInOneBlock", {}, [2048]]
      - ["AllInOneBlock", {}, [2048]]
      - ["AllInOneBlock", {}, [2048]]
      - ["AllInOneBlock", {}, [2048]]
      - ["AllInOneBlock", {}, [2048]]
      - ["AllInOneBlock", {}, [2048]]
      - ["AllInOneBlock", {}, [2048]]
      - ["AllInOneBlock", {}, [2048]]
      - ["AllInOneBlock", {}, [2048]]
      - ["AllInOneBlock", {}, [2048]]
      - ["AllInOneBlock", {}, [2048]]
      - ["AllInOneBlock", {}, [2048]]
      - ["AllInOneBlock", {}, [2048]]
      - ["AllInOneBlock", {}, [2048]]
      - ["AllInOneBlock", {}, [2048]]
      - ["AllInOneBlock", {}, [2048]]
      - ["AllInOneBlock", {}, [2048]]
      - ["AllInOneBlock", {}, [2048]]
      - ["AllInOneBlock", {}, [2048]]
      #- ["ActNorm", {}, 0]
      #- ["RNVPCouplingBlock", {"clamp_activation":"TANH", "clamp": 1.}, [1024,1024,1024]]
      #- ["InvAutoActTwoSided", {"init_pos": 1.0, "init_neg": 0.9, "learnable": False}, 0]
      #- ["PermuteRandom", {}, 0]

condition_embedder:
  - name: fff.model.ConvolutionalNeuralNetwork
    latent_dim: 2048
    ch_factor: 64
    encoder_spec: 
      - [1,4,2,1]
      - [2,4,2,1]
      - [4,4,2,1]
      - [8,4,2,1]
        #- [4,8,1,0]

lr_scheduler: "onecyclelr"
optimizer:
  name: adam
  lr: 0.00001

batch_size: 64

model_checkpoint:
  monitor: "auto"
  save_last: True
  every_n_epochs: 100
  save_top_k: 2
