model: fff.ManifoldFreeFormFlow

data_set:
  name: torus_protein

noise: 0.0

latent_distribution:
  name: manifold-uniform

lr_scheduler: "onecyclelr"

loss_weights:
  nll: 1
  noisy_reconstruction: 100
  z_reconstruction: 100
  x_sample_reconstruction: 100

models:
  - name: fff.model.MatrixFlatten
    latent_dim: data
  - name: fff.model.ResNet
    latent_dim: data
    layers_spec: [[256, 256], [256, 256], [256, 256], [256, 256], [256, 256], [256, 256]]
  - name: fff.model.MatrixFlatten
    latent_dim: data
    reverse: true

batch_size: 512

optimizer:
  name: adam
  lr: 0.001
  weight_decay: 0.001

max_epochs: 300  # General: 300, Glycine: 3000, Proline: 5000, Pre-Proline: 5000

accelerator: "gpu"
num_workers: 0
